apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ cron }}
  namespace: {{ service }}
  labels:
    app: {{ cron }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: {{ service }}-{{ cron }}
            imagePullPolicy: Never
            env:
            - name: LOG_LEVEL
              value: INFO
          restartPolicy: OnFailure
