apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ api }}
  namespace: {{ service }}
spec:
  template:
    spec:
      containers:
      - name: api
        image: {{ service }}-{{ api }}
        imagePullPolicy: Never
        command: ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "/opt/service/bin/api.py"]
        env:
        - name: LOG_LEVEL
          value: WARNING
        ports:
        - name: debug
          containerPort: 5678
          protocol: TCP
        volumeMounts:
        - name: bucket
          mountPath: /opt/service/bucket
      volumes:
      - name: config
        hostPath:
          path: /dev/null
          type: Directory
      - name: secret
        hostPath:
          path: /dev/null
          type: Directory
