apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ redis }}
  namespace: {{ service }}
spec:
  selector:
    matchLabels:
      app: {{ redis }}
  endpoints:
  - port: http
    interval: 15s
    honorLabels: true
