apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: cnc-forge
spec:
  template:
    spec:
      containers:
      - name: gui
        image: cnc-forge-gui
        imagePullPolicy: Never
