apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ gui }}
  namespace: {{ service }}
spec:
  template:
    spec:
      containers:
      - name: {{ gui }}
        image: {{ service }}-{{ gui }}
        imagePullPolicy: Never
