apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ api }}
  namespace: {{ craft }}
spec:
  selector:
    matchLabels:
      app: {{ api }}
  endpoints:
  - port: http
    interval: 15s
    honorLabels: true
